### ISSUE TITLE
FYI: proptest breaks the compiler with RUSTFLAGS="-C link-dead-code"

### ISSUE THREAD

**Issue by boustrophedon** [AltSysrq/proptest#124]
This isn't a problem that proptest can fix (probably), but building proptest with RUSTFLAGS="-C link-dead-code" leads to an ICE. The link-dead-code flag is important for accurate code coverage results.

See rust-lang/rust#52478

**Comment by AltSysrq** [comment]
0.9.1 now has a workaround. You need to opt out of the `break-dead-code` feature. If you're currently using the default feature set, you can do that with the following block in `Cargo.toml`:

```toml
[dependencies.proptest]
version = "0.9" # Only works for 0.9.1 or newer
default-features = false
# Enable all default features not known to break code coverage builds
features = ["default-code-coverage"]
```

I'm going to keep this issue open for now to help direct people to the workaround.
